-- MySQL Script generated by MySQL Workbench
-- Thu Nov 27 00:10:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema genosentinel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema genosentinel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `genosentinel` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `genosentinel` ;

-- -----------------------------------------------------
-- Table `genosentinel`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `genosentinel`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `genosentinel`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `genosentinel`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `genosentinel`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `genosentinel`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `genosentinel`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `genosentinel`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`patient` (
  `id` CHAR(36) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `birthDate` DATE NOT NULL,
  `gender` ENUM('Male', 'Female', 'Other') NOT NULL,
  `status` ENUM('Activo','Seguimiento','Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`tumortype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`tumortype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `systemAffected` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`clinicalrecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`clinicalrecord` (
  `id` CHAR(36) NOT NULL,
  `patientId` CHAR(36) NULL DEFAULT NULL,
  `tumorTypeId` INT NULL DEFAULT NULL,
  `diagnosisDate` DATE NOT NULL,
  `stage` ENUM('IA', 'IIA', 'IV') NOT NULL,
  `treatmentProtocol` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `patientId` (`patientId` ASC) VISIBLE,
  INDEX `tumorTypeId` (`tumorTypeId` ASC) VISIBLE,
  CONSTRAINT `clinicalrecord_ibfk_1`
    FOREIGN KEY (`patientId`)
    REFERENCES `genosentinel`.`patient` (`id`),
  CONSTRAINT `clinicalrecord_ibfk_2`
    FOREIGN KEY (`tumorTypeId`)
    REFERENCES `genosentinel`.`tumortype` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `genosentinel`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `genosentinel`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`gene` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `symbol` VARCHAR(50) NOT NULL,
  `fullName` VARCHAR(255) NOT NULL,
  `functionSummary` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`geneticvariant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`geneticvariant` (
  `id` CHAR(36) NOT NULL,
  `geneId` INT NULL DEFAULT NULL,
  `chromosome` VARCHAR(10) NOT NULL,
  `position` INT NOT NULL,
  `referenceBase` CHAR(1) NOT NULL,
  `alternateBase` CHAR(1) NOT NULL,
  `impact` ENUM('Missense', 'Frameshift') NOT NULL,
  `geneId_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `geneId` (`geneId` ASC) VISIBLE,
  INDEX `fk_geneId` (`geneId_id` ASC) VISIBLE,
  CONSTRAINT `fk_geneId`
    FOREIGN KEY (`geneId_id`)
    REFERENCES `genosentinel`.`gene` (`id`),
  CONSTRAINT `geneticvariant_ibfk_1`
    FOREIGN KEY (`geneId`)
    REFERENCES `genosentinel`.`gene` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`patientvariantreport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`patientvariantreport` (
  `id` CHAR(36) NOT NULL,
  `patientId` CHAR(36) NULL DEFAULT NULL,
  `variantId` CHAR(36) NULL DEFAULT NULL,
  `detectionDate` DATE NOT NULL,
  `alleleFrequency` DECIMAL(5,4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `patientId` (`patientId` ASC) VISIBLE,
  INDEX `variantId` (`variantId` ASC) VISIBLE,
  CONSTRAINT `patientvariantreport_ibfk_1`
    FOREIGN KEY (`patientId`)
    REFERENCES `genosentinel`.`patient` (`id`),
  CONSTRAINT `patientvariantreport_ibfk_2`
    FOREIGN KEY (`variantId`)
    REFERENCES `genosentinel`.`geneticvariant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genosentinel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genosentinel`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `genosentinel`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
