# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root123"
  MYSQL_PASSWORD: "apppass"
  MYSQL_USER: "appuser" # ← aquí faltaba la comilla
  DB_PASSWORD: "apppass" # ← y aquí también
  JWT_SECRET: "MySuperSecretKeyForJWTs1234567890!@#"
